### ISSUE TITLE
Some urgent queries

### ISSUE THREAD

**Issue by nefertiti007** [olejon/phpmyreservation#19]
Dear Friend,

I am deploying this on my own setup, I wanted to know if while loading reservation calendar, for example if its the 3rd day of the week, is it possible, to show only from 3rd day rather than 1st day and 2nd day of week also being displayed?

**Comment by olejon** [comment]
Like this: http://www.olejon.net/code/phpmyreservation/demotest/

?

**Comment by nefertiti007** [comment]
Hello olejon,

Thank you for the response, yes something on those lines itself. Actually I was trying to integrate this solution into my  own application, but unable to do so. due to lack of time. although I loved your script it would have served my purpose. but I am unable to cuztomise it.

1. I needed to make it a multi-user, booking for multi-service not common service.
2. I needed to customize the errors and success to be a small in page popup.
3. I also wanted the option where (these multi-services) availability will also be displayed. thus leading to user not being able to book for a service when its not available.
4. Support for mutli-time zone 

and some more features, I did try to customize it but found it real difficult as am not a programmer :( I managed to get the sessions and user data to be sync, and add some things but it dint work well.

Also, I tried displaying date next to each day, that as well I failed at.

example, a doctor appoint booking system, where there are mutiple doctors on the platform, and users can select doctors according to their availabilty. and also there will be additional filters such as number of bookings allowed, 1st booking anytime, 2nd booking can be only 10 mnts before the appointment time etc.

**Comment by olejon** [comment]
Support for multiple booking "items", years and multiple timezones is the most important things if I decide to make a new version of this, alongside a redesign (responsive design for mobile users) with Google's Material Design. Probably everything from scratch now that I code better.

If all your users are in the same timezone but the server isn't, you should be able to easily fix this by using a line of PHP code in `main.php`.

http://php.net/manual/en/function.date-default-timezone-set.php

Note: Remember to use one of the supported time zones.
