### ISSUE TITLE
Customization phpmyreservation

### ISSUE THREAD

**Issue by swrphome** [olejon/phpmyreservation#22]
Hello, many thanks for the codes.  Really neat and clean.

Meantime I have the following queries:
1.  How do you set the first day of the week to Sunday (or any day for that matter)
2.  How can the script restrict reserving past the hour (say it is already 12Noon and reservation for 11PM should be restricted)
3. How can the script make the date appear next to the day of the week (e.g. Monday - Jan 30) so users can easily identify the date.

Thanks,

Seve

**Comment by olejon** [comment]
I do not currently support this project. By modifying the code (you or get help from another developer) you should be able to do what you want.
