### ISSUE TITLE
Login page stuck on a loop when trying to login

### ISSUE THREAD

**Issue by dermot1888** [olejon/phpmyreservation#23]
The user is being added to the database ok but when i try sign in it refreshes and starts back at the login screen.

** ANY SOLUTION?? **

**Comment by prasetyaputraa** [comment]
hey, I experienced the same issue. do you have any workarounds??

**Comment by olejon** [comment]
I seem to have the same problem from the Android app, not sure if it's because of my proxy. If you are trying from the Android app, try from a computer instead, it works fine here. Then you are authorized on all devices.

**Comment by olejon** [comment]
Turned out it was just the proxy for me (uses squidGuard with various filters). I can authorize fine with the Android app and other devices. Can you describe more detailed what you do and what happens?

**Comment by olejon** [comment]
Sorry I thought this issue was for another project. Does it work in the demo? I don't support this project anymore, so if you don't describe more detailed what you do and what happens, I don't have time for it. Sorry.

**Comment by olejon** [comment]
Closed due to no answer.
